apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870  # Web UI
            - containerPort: 9000  # HDFS 服务
          env:
            - name: CLUSTER_NAME
              value: "itmo_cluster"
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://namenode:9000"
            - name: HDFS_CONF_dfs_replication
              value: "1"
          volumeMounts:
            - name: hdfs-storage
              mountPath: /hadoop/dfs/name
      volumes:
        - name: hdfs-storage
          persistentVolumeClaim:
            claimName: namenode-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
    - name: web
      port: 9870
      targetPort: 9870
    - name: hdfs
      port: 9000
      targetPort: 9000