apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-init
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  init.sql: |
    {{- .Values.postgresql.initScript | nindent 4 }}