apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.passwordKey }}: {{ .Values.postgresql.password | b64enc | quote }}