apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}