apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS processed_data (
      fat_100g FLOAT,
      carbohydrates_100g FLOAT,
      proteins_100g FLOAT,
      features TEXT,
      scaled_features TEXT
    );