apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-spark-rolebinding
  labels:
    {{- include "datamart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-spark-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.spark.serviceAccount }}
  namespace: {{ .Release.Namespace }}