apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-spark-role
  labels:
    {{- include "datamart.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - pods
    - services
    - endpoints
    - configmaps
    - persistentvolumeclaims
  verbs:
    - create
    - get
    - watch
    - list
    - delete
    - patch