apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.passwordSecret }}
  labels:
    {{- include "datamart.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.db.passwordKey }}: {{ .Values.db.password | b64enc | quote }}