apiVersion: v1
kind: ConfigMap
metadata:
  name: model-training-config
data:
  spark-config.json: {{ .Values.sparkConfig | quote }}
  DB_HOST: {{ .Values.db.host }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name }}
  DB_USER: {{ .Values.db.user }}