{{- $existingSecret := lookup "v1" "Secret" "default" .Values.db.passwordSecret }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.passwordSecret }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
{{- end }}